package pk.raahat.ai

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.animation.*
import androidx.compose.animation.core.*
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.*
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.draw.*
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.*
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.*
import androidx.lifecycle.viewmodel.compose.viewModel
import kotlin.math.*

private val Navy=Color(0xFF06111D); private val Panel=Color(0xFF0D2233); private val Cyan=Color(0xFF27D9FF)
private val Emerald=Color(0xFF42E7A5); private val Amber=Color(0xFFFFC857); private val Red=Color(0xFFFF4967); private val Soft=Color(0xFFDCEAF3)

class MainActivity:ComponentActivity(){ override fun onCreate(b:Bundle?){super.onCreate(b);setContent { RaahatTheme { RaahatApp() } }} }

@Composable fun RaahatTheme(content: @Composable () -> Unit){ MaterialTheme(colorScheme=darkColorScheme(primary=Cyan,secondary=Emerald,background=Navy,surface=Panel,onBackground=Soft,onSurface=Soft,error=Red),content=content) }

@Composable fun RaahatApp(vm:RaahatViewModel= viewModel()){
    Surface(modifier=Modifier.fillMaxSize(),color=Navy,contentColor=Soft){ Box(Modifier.fillMaxSize().background(Brush.verticalGradient(listOf(Navy,Color(0xFF071B28),Navy)))){
        AnimatedContent(vm.screen,transitionSpec={fadeIn(tween(450))+slideInHorizontally{it/8} togetherWith fadeOut(tween(250))},label="screen") { s ->
            when(s){ Screen.SPLASH->Splash(); Screen.ROLE->Role(vm); Screen.CITIZEN->Citizen(vm); Screen.REPORT->Report(vm); Screen.VERIFY->Verify(vm); Screen.COMMAND->Command(vm); Screen.INCIDENT->Incident(vm); Screen.STRATEGY->Strategy(vm); Screen.EXECUTE->Execute(vm); Screen.IMPACT->Impact(vm); Screen.CITY->CityPulse(vm); Screen.COPILOT->Copilot(vm) }
        }
    } }
}

@Composable fun Splash(){ Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){ Radar(260.dp); Column(horizontalAlignment=Alignment.CenterHorizontally){ Logo(92.dp); Spacer(Modifier.height(24.dp)); Text("RAAHAT AI",fontSize=34.sp,fontWeight=FontWeight.Black,letterSpacing=4.sp); Text("URBAN FLOOD INTELLIGENCE",color=Cyan,fontSize=11.sp,letterSpacing=2.sp); Spacer(Modifier.height(48.dp)); Text("See the flood before it spreads.",color=Soft.copy(.8f)) } } }

@Composable fun Role(vm:RaahatViewModel){ Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.SpaceBetween){ Column{ Spacer(Modifier.height(46.dp)); Row(verticalAlignment=Alignment.CenterVertically){Logo(48.dp);Spacer(Modifier.width(14.dp));Column{Text("RAAHAT AI",fontWeight=FontWeight.Black,fontSize=24.sp);Live(if(vm.backendHealth.available)"BACKEND LIVE" else "OFFLINE SAFE")}};Spacer(Modifier.height(54.dp));Text("Choose your\nexperience",fontSize=38.sp,lineHeight=42.sp,fontWeight=FontWeight.Bold);Text("One intelligence network. Two ways to protect the city.",color=Soft.copy(.65f),modifier=Modifier.padding(top=12.dp)) }; Column(verticalArrangement=Arrangement.spacedBy(14.dp)){ RoleCard(Icons.Default.Person,"CITIZEN","Report danger. Stay informed.",Cyan){vm.go(Screen.CITIZEN)};RoleCard(Icons.Default.Radar,"EMERGENCY COMMAND","Predict. Decide. Coordinate.",Red){vm.go(Screen.COMMAND)}; OutlinedButton({vm.startDemo()},Modifier.fillMaxWidth().height(56.dp),shape=RoundedCornerShape(18.dp),border=BorderStroke(1.dp,Cyan.copy(.4f))){Icon(Icons.Default.PlayArrow,null);Spacer(Modifier.width(8.dp));Text("LAUNCH DEMO SCENARIO")}; Text("DETECT  →  VERIFY  →  PREDICT  →  RESPOND",fontSize=10.sp,letterSpacing=1.sp,color=Soft.copy(.45f),modifier=Modifier.align(Alignment.CenterHorizontally).padding(vertical=16.dp)) } } }

@Composable fun RoleCard(icon:ImageVector,title:String,sub:String,color:Color,onClick:()->Unit){ Card(onClick,Modifier.fillMaxWidth().height(116.dp),shape=RoundedCornerShape(24.dp),colors=CardDefaults.cardColors(containerColor=Panel.copy(.9f)),border=BorderStroke(1.dp,color.copy(.28f))){Row(Modifier.fillMaxSize().padding(22.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(62.dp).background(color.copy(.12f),RoundedCornerShape(20.dp)),contentAlignment=Alignment.Center){Icon(icon,null,tint=color,modifier=Modifier.size(30.dp))};Spacer(Modifier.width(18.dp));Column(Modifier.weight(1f)){Text(title,fontWeight=FontWeight.Bold,letterSpacing=1.sp);Text(sub,color=Soft.copy(.6f),fontSize=13.sp)};Icon(Icons.Default.ArrowForward,null,tint=color)}}}

@Composable fun Citizen(vm:RaahatViewModel){ Shell("CITIZEN NETWORK",onBack={vm.go(Screen.ROLE)}){ Text("Good evening",color=Soft.copy(.6f));Text("Flood Intelligence\nfor Islamabad",fontSize=30.sp,lineHeight=34.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(20.dp));Glass{Row(verticalAlignment=Alignment.CenterVertically){RiskRing(48,"MODERATE",Amber,88.dp);Spacer(Modifier.width(18.dp));Column{Label("CURRENT RISK AROUND YOU");Text("G-10",fontSize=24.sp,fontWeight=FontWeight.Bold);Text("18 mm/hr rainfall  •  1.8 km away",fontSize=12.sp,color=Soft.copy(.6f))}}};Spacer(Modifier.height(14.dp));MiniMap();Spacer(Modifier.height(18.dp));Button({vm.go(Screen.REPORT)},Modifier.fillMaxWidth().height(62.dp),shape=RoundedCornerShape(20.dp)){Icon(Icons.Default.AddAlert,null);Spacer(Modifier.width(10.dp));Text("REPORT FLOODING",fontWeight=FontWeight.Bold)}; SectionTitle("LOCAL INTELLIGENCE"); Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){Metric("03","Reports",Modifier.weight(1f));Metric("2","Risk zones",Modifier.weight(1f));Metric("7m","Update",Modifier.weight(1f))} } }

@Composable fun Report(vm:RaahatViewModel){Shell("INTELLIGENT REPORT",{vm.go(Screen.CITIZEN)}){Label("LOCATION · AUTO-DETECTED");Glass{Row{Icon(Icons.Default.LocationOn,null,tint=Cyan);Spacer(Modifier.width(10.dp));Column{Text("G-10 Underpass, Islamabad",fontWeight=FontWeight.Bold);Text("GPS accuracy ± 8 metres",fontSize=11.sp,color=Emerald)}}};SectionTitle("WATER LEVEL");ChoiceRow(listOf("Road wet","Ankle deep","Knee deep","Wheel level","Dangerous"),vm.selectedLevel){vm.selectedLevel=it};SectionTitle("WHAT'S HAPPENING?");ChoiceRow(listOf("Drain overflowing","Road blocked","Vehicle stuck","Person at risk","Underpass flooding","Water rising quickly"),vm.selectedSituation){vm.selectedSituation=it};Spacer(Modifier.height(18.dp));OutlinedTextField("Water rising near the eastern ramp…",{},Modifier.fillMaxWidth().height(100.dp),label={Text("Description")},shape=RoundedCornerShape(16.dp));Spacer(Modifier.height(12.dp));OutlinedButton({},Modifier.fillMaxWidth().height(54.dp),shape=RoundedCornerShape(16.dp)){Icon(Icons.Default.AddAPhoto,null);Spacer(Modifier.width(8.dp));Text("ADD PHOTO EVIDENCE")};Spacer(Modifier.height(24.dp));Button({vm.verify()},Modifier.fillMaxWidth().height(60.dp),shape=RoundedCornerShape(18.dp)){Icon(Icons.Default.AutoAwesome,null);Spacer(Modifier.width(8.dp));Text("SEND INTELLIGENT REPORT",fontWeight=FontWeight.Bold)}}}

@Composable fun ChoiceRow(items:List<String>,selected:String,onSelect:(String)->Unit){FlowRow(horizontalArrangement=Arrangement.spacedBy(8.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){items.forEach{FilterChip(it==selected,{onSelect(it)},{Text(it)},leadingIcon=if(it==selected){{Icon(Icons.Default.Check,null,Modifier.size(16.dp))}}else null)}}}

@Composable fun Verify(vm:RaahatViewModel){Box(Modifier.fillMaxSize().padding(26.dp),contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){Radar(180.dp);Text(if(vm.verifiedSignals<4)"Cross-checking your report…" else "Report Verified",fontSize=26.sp,fontWeight=FontWeight.Bold,textAlign=TextAlign.Center);Spacer(Modifier.height(24.dp));listOf("Citizen Signal","Weather Signal","Traffic Signal","Area Risk Model").forEachIndexed{i,s->Row(Modifier.fillMaxWidth().padding(vertical=8.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(30.dp).background(if(i<vm.verifiedSignals)Emerald.copy(.15f) else Soft.copy(.06f),CircleShape),contentAlignment=Alignment.Center){if(i<vm.verifiedSignals)Icon(Icons.Default.Check,null,tint=Emerald,modifier=Modifier.size(18.dp))else CircularProgressIndicator(Modifier.size(16.dp),strokeWidth=1.dp)};Spacer(Modifier.width(12.dp));Text(s);Spacer(Modifier.weight(1f));if(i<vm.verifiedSignals)Text("VERIFIED",fontSize=10.sp,color=Emerald)}};AnimatedVisibility(vm.verifiedSignals==4){Glass{Column(horizontalAlignment=Alignment.CenterHorizontally){Text("88% CONFIDENCE",color=Cyan,fontWeight=FontWeight.Bold);Text("Signals agree within 600 metres. RAAHAT AI escalated this incident to HIGH severity.",textAlign=TextAlign.Center,fontSize=13.sp,modifier=Modifier.padding(vertical=12.dp));Button({vm.go(Screen.CITIZEN)}){Text("VIEW LOCAL RISK")}}}}}}}

@Composable fun Command(vm:RaahatViewModel){Shell("RAAHAT COMMAND",{vm.go(Screen.ROLE)},bottom={BottomNav(vm,Screen.COMMAND)}){Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("Islamabad",fontSize=30.sp,fontWeight=FontWeight.Bold);Text("FLOOD INTELLIGENCE",color=Cyan,fontSize=11.sp,letterSpacing=2.sp)};Live("LIVE · 18:57")};if(vm.demo) DemoStrip();Spacer(Modifier.height(16.dp));Row(horizontalArrangement=Arrangement.spacedBy(9.dp)){Metric("07","Active",Modifier.weight(1f),Cyan);Metric("02","Critical",Modifier.weight(1f),Red);Metric("04","Teams",Modifier.weight(1f),Emerald)};Spacer(Modifier.height(10.dp));Row(horizontalArrangement=Arrangement.spacedBy(9.dp)){Metric("3,820","Warned",Modifier.weight(1f));Metric("7.4m","Avg response",Modifier.weight(1f))};Spacer(Modifier.height(16.dp));IncidentMap{vm.go(Screen.INCIDENT)};SectionTitle("PRIORITY INCIDENTS");IncidentRow("G-10 Underpass","CRITICAL · 94% confidence","5 reports · 36 mm/hr",Red){vm.go(Screen.INCIDENT)};IncidentRow("I-8 Markaz","HIGH · 82% confidence","3 reports · 28 mm/hr",Color(0xFFFF8A4C)){};IncidentRow("F-10 Service Road","MODERATE · 71% confidence","2 reports · 18 mm/hr",Amber){} }}

@Composable fun Incident(vm:RaahatViewModel){Shell("DIGITAL TWIN · G-10",{vm.go(Screen.COMMAND)}){Row(verticalAlignment=Alignment.CenterVertically){RiskRing(91,"CRITICAL",Red,126.dp);Spacer(Modifier.width(22.dp));Column{Text("G-10 Underpass",fontSize=25.sp,fontWeight=FontWeight.Bold);Text("AI CONFIDENCE 94%",color=Cyan,fontWeight=FontWeight.Bold);Live("ESCALATING")}};SectionTitle("SIGNAL FUSION");Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Metric("5","Reports",Modifier.weight(1f));Metric("36","mm/hr",Modifier.weight(1f));Metric("89%","Traffic",Modifier.weight(1f))};Spacer(Modifier.height(8.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Metric("22%","Drainage",Modifier.weight(1f));Metric("7","km/h",Modifier.weight(1f));Metric("1,240","Exposed",Modifier.weight(1f))};SectionTitle("WHY DID AI ESCALATE THIS?");Glass{Text("RAAHAT detected agreement across four independent signals. Reports accelerated, rainfall crossed the severe threshold, congestion surged, and drainage capacity is insufficient.",fontSize=13.sp,lineHeight=20.sp)};SectionTitle("FLOOD PATH FORECAST · SIMULATED");vm.incident.predictions.forEach{Forecast(it)};SectionTitle("INCIDENT TIMELINE");vm.timeline.forEachIndexed{i,e->Timeline(e.first,e.second,i==vm.timeline.lastIndex)};Spacer(Modifier.height(18.dp));Button({vm.go(Screen.STRATEGY)},Modifier.fillMaxWidth().height(58.dp),shape=RoundedCornerShape(18.dp)){Icon(Icons.Default.Tune,null);Spacer(Modifier.width(8.dp));Text("SIMULATE RESPONSE OPTIONS")}}}

@Composable fun Strategy(vm:RaahatViewModel){Shell("RESPONSE SIMULATOR",{vm.go(Screen.INCIDENT)}){Text("Three strategies. One measurable decision.",fontSize=22.sp,fontWeight=FontWeight.Bold);Text("RAAHAT compares response time, resources, traffic and population protection.",color=Soft.copy(.6f),fontSize=13.sp);Spacer(Modifier.height(18.dp));vm.strategies.forEach{p->Card(Modifier.fillMaxWidth().padding(bottom=12.dp),shape=RoundedCornerShape(22.dp),colors=CardDefaults.cardColors(containerColor=if(p.recommended)Color(0xFF0C3040) else Panel),border=BorderStroke(1.dp,if(p.recommended)Cyan.copy(.7f) else Soft.copy(.08f))){Column(Modifier.padding(18.dp)){Row{Text(p.name,fontWeight=FontWeight.Bold,modifier=Modifier.weight(1f));if(p.recommended)Pill("AI RECOMMENDED",Cyan)};Spacer(Modifier.height(12.dp));Row{SimStat("-${p.congestionReduction}%","Congestion",Modifier.weight(1f));SimStat("${p.protected}","Protected",Modifier.weight(1f));SimStat(p.cost,"Cost",Modifier.weight(1f))};p.actions.forEach{Text("✓  ${it.title}",fontSize=12.sp,color=Soft.copy(.75f),modifier=Modifier.padding(top=6.dp))}}}};Glass{Text("Why Strategy B?",fontWeight=FontWeight.Bold,color=Cyan);Text("Best balance between response time, available resources, congestion reduction and population protection.",fontSize=13.sp,modifier=Modifier.padding(top=6.dp))};Spacer(Modifier.height(20.dp));Button({vm.execute()},Modifier.fillMaxWidth().height(64.dp),colors=ButtonDefaults.buttonColors(containerColor=Red),shape=RoundedCornerShape(20.dp)){Icon(Icons.Default.Bolt,null);Spacer(Modifier.width(8.dp));Text("EXECUTE RESPONSE",fontWeight=FontWeight.Black)}}}

@Composable fun Execute(vm:RaahatViewModel){Box(Modifier.fillMaxSize().padding(26.dp),contentAlignment=Alignment.Center){Column{Label("AI RESPONSE ORCHESTRATOR");Text("Coordinating city response",fontSize=30.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(28.dp));listOf("Closing G-10 underpass","Recalculating traffic","Creating dispatch ticket RH-2048","Sending 1,240 resident warnings","Monitoring G-10/2").forEachIndexed{i,s->Row(Modifier.fillMaxWidth().padding(vertical=12.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(38.dp).background(if(i<vm.executionStep)Emerald.copy(.16f)else Cyan.copy(.08f),CircleShape),contentAlignment=Alignment.Center){if(i<vm.executionStep)Icon(Icons.Default.Check,null,tint=Emerald)else if(i==vm.executionStep)CircularProgressIndicator(Modifier.size(20.dp),strokeWidth=2.dp) else Text("${i+1}",color=Soft.copy(.4f))};Spacer(Modifier.width(14.dp));Column{Text(s,fontWeight=FontWeight.SemiBold);if(i==2&&i<vm.executionStep)Text("D-07 · EN ROUTE · ETA 9 MIN",fontSize=10.sp,color=Cyan);if(i==3&&i<vm.executionStep)Text("SMS ✓   PUSH ✓   COMMUNITY ✓",fontSize=10.sp,color=Emerald)}}}}}}

@Composable fun Impact(vm:RaahatViewModel){Shell("RESPONSE IMPACT",{vm.go(Screen.COMMAND)},bottom={BottomNav(vm,Screen.IMPACT)}){Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("Digital Twin",fontSize=30.sp,fontWeight=FontWeight.Bold);Text("BEFORE → AFTER",color=Cyan,letterSpacing=2.sp,fontSize=11.sp)};Pill("STABILIZING",Emerald)};Spacer(Modifier.height(18.dp));BeforeAfter("Flood risk","CRITICAL","HIGH",Red,Amber);BeforeAfter("Congestion","89%","37%",Red,Emerald);BeforeAfter("Population exposed","1,240","310",Red,Emerald);BeforeAfter("Road status","OPEN · UNSAFE","CLOSED",Red,Emerald);BeforeAfter("Response teams","0","2",Soft,Emerald);SectionTitle("MEASURED OUTCOME");Row(horizontalArrangement=Arrangement.spacedBy(9.dp)){ImpactRing(61,"Risk",Modifier.weight(1f));ImpactRing(52,"Traffic",Modifier.weight(1f));ImpactRing(75,"Exposure",Modifier.weight(1f))};Spacer(Modifier.height(18.dp));Glass{Row{Icon(Icons.Default.Verified,null,tint=Emerald);Spacer(Modifier.width(10.dp));Column{Text("Response successfully orchestrated",fontWeight=FontWeight.Bold);Text("Ticket RH-2048 · D-07 en route · 1,240 alerts delivered",fontSize=11.sp,color=Soft.copy(.6f))}}};Spacer(Modifier.height(18.dp));Button({vm.go(Screen.CITY)},Modifier.fillMaxWidth()){Text("VIEW CITY PULSE")}}}

@Composable fun CityPulse(vm:RaahatViewModel){Shell("CITY PULSE",{vm.go(Screen.COMMAND)},bottom={BottomNav(vm,Screen.CITY)}){Text("Islamabad resilience",fontSize=30.sp,fontWeight=FontWeight.Bold);Glass{Row(verticalAlignment=Alignment.CenterVertically){RiskRing(78,"READY",Emerald,105.dp);Spacer(Modifier.width(18.dp));Column{Text("Flood Readiness",color=Soft.copy(.6f));Text("78 / 100",fontSize=26.sp,fontWeight=FontWeight.Bold);Text("Operations synchronized",color=Emerald,fontSize=12.sp)}}};SectionTitle("NEIGHBORHOOD RISK");listOf("G-10" to 91,"I-8" to 64,"F-10" to 48,"G-11" to 32,"Blue Area" to 18).forEach{(n,v)->Row(Modifier.fillMaxWidth().padding(vertical=8.dp),verticalAlignment=Alignment.CenterVertically){Text(n,Modifier.width(82.dp),fontWeight=FontWeight.Bold);LinearProgressIndicator({v/100f},Modifier.weight(1f).height(8.dp).clip(CircleShape),color=severityColor(v),trackColor=Soft.copy(.08f));Text("$v",Modifier.width(40.dp),textAlign=TextAlign.End,color=severityColor(v))}};SectionTitle("CITY SIGNALS");Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Metric("36","Rain mm",Modifier.weight(1f));Metric("42%","Slowdown",Modifier.weight(1f));Metric("68%","Drain pressure",Modifier.weight(1f))}}}

@Composable fun Copilot(vm:RaahatViewModel){Shell("RAAHAT COPILOT",{vm.go(Screen.COMMAND)},bottom={BottomNav(vm,Screen.COPILOT)}){Row(verticalAlignment=Alignment.CenterVertically){Logo(52.dp);Spacer(Modifier.width(12.dp));Column{Text("Command intelligence",fontSize=24.sp,fontWeight=FontWeight.Bold);Live("AI READY")}};Spacer(Modifier.height(22.dp));Glass{Text(if(vm.copilotText.isBlank())"Ask me about risk, response options, available resources, or predicted impact." else vm.copilotText,lineHeight=21.sp)};SectionTitle("SUGGESTED COMMANDS");listOf("What is the most dangerous area?","Which team should I dispatch?","What happens if we don't close it?","Give me a 30-second situation report").forEach{q->OutlinedButton({vm.answer(q)},Modifier.fillMaxWidth().padding(bottom=8.dp),shape=RoundedCornerShape(16.dp),contentPadding=PaddingValues(15.dp)){Icon(Icons.Default.AutoAwesome,null,Modifier.size(17.dp));Spacer(Modifier.width(9.dp));Text(q,Modifier.weight(1f),textAlign=TextAlign.Start);Icon(Icons.Default.ArrowForward,null,Modifier.size(16.dp))}}}}

@Composable fun Shell(title:String,onBack:()->Unit,bottom:(@Composable () -> Unit)?=null,content:@Composable ColumnScope.()->Unit){Scaffold(containerColor=Color.Transparent,topBar={Row(Modifier.fillMaxWidth().statusBarsPadding().padding(16.dp),verticalAlignment=Alignment.CenterVertically){IconButton(onBack){Icon(Icons.Default.ArrowBack,null)};Text(title,fontWeight=FontWeight.Bold,letterSpacing=1.sp);Spacer(Modifier.weight(1f));Box(Modifier.size(8.dp).background(Emerald,CircleShape))}},bottomBar={bottom?.invoke()}){p->Column(Modifier.fillMaxSize().padding(p).padding(horizontal=20.dp).verticalScroll(rememberScrollState()).padding(bottom=24.dp),content=content)}}
@Composable fun BottomNav(vm:RaahatViewModel,current:Screen){NavigationBar(containerColor=Color(0xF20A1B28)){listOf(Triple(Screen.COMMAND,Icons.Default.SpaceDashboard,"Command"),Triple(Screen.CITY,Icons.Default.Insights,"City Pulse"),Triple(Screen.COPILOT,Icons.Default.AutoAwesome,"Copilot")).forEach{(s,i,l)->NavigationBarItem(selected=current==s,onClick={vm.go(s)},icon={Icon(i,null)},label={Text(l,fontSize=10.sp)},colors=NavigationBarItemDefaults.colors(indicatorColor=Cyan.copy(.12f),selectedIconColor=Cyan,unselectedIconColor=Soft.copy(.45f)))}}}

@Composable fun IncidentMap(onTap:()->Unit){Card(onClick=onTap,modifier=Modifier.fillMaxWidth().height(260.dp),shape=RoundedCornerShape(24.dp),colors=CardDefaults.cardColors(containerColor=Color(0xFF091B27)),border=BorderStroke(1.dp,Cyan.copy(.15f))){Box(Modifier.fillMaxSize()){Canvas(Modifier.fillMaxSize()){for(i in 0..8){drawLine(Color(0xFF143344),Offset(i*size.width/8,0f),Offset(i*size.width/8,size.height),1f);drawLine(Color(0xFF143344),Offset(0f,i*size.height/8),Offset(size.width,i*size.height/8),1f)};val road=Path().apply{moveTo(0f,size.height*.72f);cubicTo(size.width*.3f,size.height*.35f,size.width*.6f,size.height*.85f,size.width,size.height*.32f)};drawPath(road,Color(0xFF25495B),style=Stroke(18f));drawPath(road,Cyan.copy(.45f),style=Stroke(3f));drawCircle(Red.copy(.15f),70f,Offset(size.width*.52f,size.height*.52f));drawCircle(Red.copy(.35f),42f,Offset(size.width*.52f,size.height*.52f));drawCircle(Red,14f,Offset(size.width*.52f,size.height*.52f));drawCircle(Amber,9f,Offset(size.width*.23f,size.height*.3f));drawCircle(Emerald,8f,Offset(size.width*.8f,size.height*.72f))};Pill("AI RISK MAP · LIVE",Cyan,Modifier.padding(14.dp).align(Alignment.TopStart));Column(Modifier.align(Alignment.BottomStart).padding(16.dp)){Text("G-10 UNDERPASS",fontWeight=FontWeight.Bold);Text("CRITICAL · Tap to open Digital Twin",color=Red,fontSize=11.sp)}}}}
@Composable fun MiniMap(){Box(Modifier.fillMaxWidth().height(140.dp).background(Color(0xFF091C29),RoundedCornerShape(22.dp))){Canvas(Modifier.fillMaxSize()){drawCircle(Amber.copy(.14f),75f,center);drawCircle(Amber.copy(.3f),45f,center);drawCircle(Cyan,10f,center);drawLine(Cyan.copy(.25f),Offset(0f,size.height*.7f),Offset(size.width,size.height*.35f),5f)};Pill("NEIGHBORHOOD SCAN",Cyan,Modifier.padding(12.dp));Text("YOU",fontSize=9.sp,color=Cyan,modifier=Modifier.align(Alignment.Center).offset(y=22.dp))}}
@Composable fun Radar(size:Dp){val t=rememberInfiniteTransition(label="radar");val p by t.animateFloat(0f,1f,infiniteRepeatable(tween(1800),RepeatMode.Restart),label="pulse");Canvas(Modifier.size(size)){repeat(3){i->drawCircle(Cyan.copy(alpha=((1-p)*(.25f-i*.04f)).coerceAtLeast(0f)),radius=this.size.minDimension/2*(p+i*.28f).coerceAtMost(1f),style=Stroke(2f))};drawLine(Cyan.copy(.3f),center,Offset(center.x+cos(p*6.28f)*center.x,center.y+sin(p*6.28f)*center.y),2f)}}
@Composable fun Logo(size:Dp){Box(Modifier.size(size).background(Brush.linearGradient(listOf(Cyan,Color(0xFF3478FF))),RoundedCornerShape(size*.28f)).shadow(20.dp,RoundedCornerShape(size*.28f)),contentAlignment=Alignment.Center){Icon(Icons.Default.WaterDrop,null,tint=Navy,modifier=Modifier.size(size*.55f))}}
@Composable fun Glass(content: @Composable ColumnScope.() -> Unit){Column(Modifier.fillMaxWidth().background(Soft.copy(.055f),RoundedCornerShape(20.dp)).border(1.dp,Soft.copy(.09f),RoundedCornerShape(20.dp)).padding(18.dp),content=content)}
@Composable fun Metric(value:String,label:String,mod:Modifier,color:Color=Soft){Column(mod.background(Soft.copy(.055f),RoundedCornerShape(16.dp)).padding(13.dp)){Text(value,fontSize=22.sp,fontWeight=FontWeight.Bold,color=color);Text(label,fontSize=10.sp,color=Soft.copy(.55f))}}
@Composable fun RiskRing(value:Int,label:String,color:Color,size:Dp){Box(Modifier.size(size),contentAlignment=Alignment.Center){Canvas(Modifier.fillMaxSize()){drawArc(Soft.copy(.08f),-90f,360f,false,style=Stroke(9f,cap=StrokeCap.Round));drawArc(color,-90f,value*3.6f,false,style=Stroke(9f,cap=StrokeCap.Round))};Column(horizontalAlignment=Alignment.CenterHorizontally){Text("$value",fontSize=(size.value*.2).sp,fontWeight=FontWeight.Black);Text(label,fontSize=8.sp,color=color,fontWeight=FontWeight.Bold)}}}
@Composable fun SectionTitle(t:String){Text(t,fontSize=11.sp,color=Soft.copy(.55f),letterSpacing=1.4.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=24.dp,bottom=10.dp))}
@Composable fun Label(t:String){Text(t,fontSize=10.sp,color=Cyan,letterSpacing=1.4.sp,fontWeight=FontWeight.Bold)}
@Composable fun Live(t:String){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(6.dp).background(Emerald,CircleShape));Spacer(Modifier.width(6.dp));Text(t,fontSize=9.sp,color=Emerald,letterSpacing=1.sp)}}
@Composable fun Pill(t:String,c:Color,mod:Modifier=Modifier){Text(t,fontSize=9.sp,color=c,fontWeight=FontWeight.Bold,letterSpacing=.7.sp,modifier=mod.background(c.copy(.12f),CircleShape).border(1.dp,c.copy(.35f),CircleShape).padding(horizontal=10.dp,vertical=6.dp))}
@Composable fun IncidentRow(name:String,status:String,sub:String,color:Color,onClick:()->Unit){Row(Modifier.fillMaxWidth().clickable(onClick=onClick).padding(vertical=11.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(12.dp).background(color,CircleShape));Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(name,fontWeight=FontWeight.Bold);Text(sub,fontSize=11.sp,color=Soft.copy(.5f))};Text(status,fontSize=9.sp,color=color);Icon(Icons.Default.ChevronRight,null,tint=Soft.copy(.4f))}}
@Composable fun Forecast(p:PredictedZone){Row(Modifier.fillMaxWidth().padding(vertical=7.dp).background(Cyan.copy(.05f),RoundedCornerShape(15.dp)).padding(13.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.TrendingUp,null,tint=Cyan);Spacer(Modifier.width(10.dp));Column(Modifier.weight(1f)){Text(p.name,fontWeight=FontWeight.Bold);Text("Expected ${p.eta}",fontSize=11.sp,color=Soft.copy(.55f))};Text("${p.probability}%",fontSize=20.sp,fontWeight=FontWeight.Bold,color=if(p.probability>60)Red else Amber)}}
@Composable fun Timeline(time:String,title:String,last:Boolean){Row(Modifier.height(46.dp)){Column(horizontalAlignment=Alignment.CenterHorizontally){Box(Modifier.size(9.dp).background(if(last)Red else Cyan,CircleShape));if(!last)Box(Modifier.width(1.dp).weight(1f).background(Cyan.copy(.25f)))};Text(time,Modifier.width(58.dp).padding(start=10.dp),fontSize=11.sp,color=Cyan);Text(title,fontSize=12.sp,color=if(last)Soft else Soft.copy(.7f))}}
@Composable fun SimStat(v:String,l:String,m:Modifier){Column(m){Text(v,fontSize=19.sp,fontWeight=FontWeight.Bold,color=Cyan);Text(l,fontSize=9.sp,color=Soft.copy(.5f))}}
@Composable fun BeforeAfter(label:String,before:String,after:String,beforeC:Color,afterC:Color){Row(Modifier.fillMaxWidth().padding(vertical=8.dp).background(Soft.copy(.04f),RoundedCornerShape(14.dp)).padding(13.dp),verticalAlignment=Alignment.CenterVertically){Text(label,Modifier.weight(1f),fontSize=12.sp);Text(before,color=beforeC,fontSize=12.sp);Icon(Icons.Default.ArrowForward,null,tint=Soft.copy(.35f),modifier=Modifier.padding(horizontal=9.dp).size(15.dp));Text(after,color=afterC,fontWeight=FontWeight.Bold,fontSize=12.sp)}}
@Composable fun ImpactRing(v:Int,l:String,m:Modifier){Column(m,horizontalAlignment=Alignment.CenterHorizontally){RiskRing(v,"%",Emerald,82.dp);Text(l,fontSize=11.sp,modifier=Modifier.padding(top=7.dp))}}
@Composable fun DemoStrip(){Row(Modifier.fillMaxWidth().padding(top=12.dp).background(Cyan.copy(.1f),RoundedCornerShape(12.dp)).padding(10.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.PlayCircle,null,tint=Cyan);Spacer(Modifier.width(8.dp));Text("DEMO SCENARIO ACTIVE · G-10",color=Cyan,fontSize=11.sp,fontWeight=FontWeight.Bold)}}
fun severityColor(v:Int)=when(v){in 0..29->Emerald;in 30..49->Amber;in 50..69->Color(0xFFFF8A4C);else->Red}
